enum descriptions{
    ABOUTME = "I am currently studying the 3rd semester of Software Engineering at PUCRS. During this time, I have developed good programming skills and developed some projects, which I will share on this website. In addition, I love to seek to evolve as a person and increase my knowledge about programming every day. Here i would like to show you a little of my work, always seeking to solve real problems through programming.",
    //Atualmente estou cursando o 3º semestre de Engenharia de Software na PUCRS, nesse tempo de formação desenvolvi bons conhecimentos de programação e alguns projetos, os quais irei compartilhar nesse site. Além disso, adoro buscar diariamente evoluir como pessoa e aumentar meus conhecimentos sobre programação. Venho mostrar um pouco do meu trabalho, sempre procurando resolver problemas reais por meio da programação.
    HTML = "Markup language used to structure and present content on the web. Defines elements such as text, images, and links.",
    //Linguagem de marcação usada para estruturar e apresentar conteúdo na web. Define elementos como textos, imagens e links.",
    CSS = "Style sheets used to style the layout of HTML pages, controlling colors, fonts, and arrangement of elements.",
    //Folhas de estilo usadas para estilizar o layout de páginas HTML, controlando cores, fontes, e disposição de elementos.",
    Java = "Object-oriented programming language, widely used for backend and Android application development.",
    //Linguagem de programação orientada a objetos, amplamente usada para desenvolvimento de aplicações backend e Android.",
    JavaScript = "Web scripting language, allowing you to create interactivity and manipulate the DOM in HTML pages.",
    //Linguagem de script para web, permitindo criar interatividade e manipular o DOM em páginas HTML.",
    TypeScript = "A superset of JavaScript that adds static typing, making code more robust and easier to maintain.",
    //Superconjunto do JavaScript que adiciona tipagem estática, tornando o código mais robusto e fácil de manter.",
    GIT = "Distributed version control system to track project changes and collaborate efficiently.",
    //Sistema de controle de versão distribuído para rastrear alterações em projetos e colaborar de forma eficiente.",
    React = "Distributed version control system for tracking project changes and collaborating efficiently.",
    //Biblioteca JavaScript para construção de interfaces de usuário, baseada em componentes e gerenciamento eficiente de estado.",
    Tailwind = "CSS framework utility that makes it easy to create custom layouts directly in HTML.",
    //Framework CSS utilitário que facilita a criação de layouts personalizados diretamente no HTML.",
    Flutter = "Flutter is an open-source framework from Google for developing cross-platform applications, allowing you to create native interfaces for Android, iOS, web and desktop.",
    //Flutter é um framework open-source do Google para desenvolvimento de aplicativos multiplataforma, permitindo criar interfaces nativas para Android, iOS, web e desktop.",
    NodeJS = "Backend JavaScript environment that allows code execution on the server. Ideal for APIs and real-time applications.",
    //Ambiente JavaScript de backend que permite a execução de código no servidor. Ideal para APIs e aplicações em tempo real.",
    Prisma = "ORM (Object-Relational Mapping) that facilitates interaction with databases, automating complex queries.",
    //ORM (Object-Relational Mapping) que facilita a interação com bancos de dados, automatizando queries complexas.",
    MongoDB = "Document-oriented NoSQL database suitable for applications with large volumes of unstructured data.",
    //Banco de dados NoSQL orientado a documentos, adequado para aplicações com grandes volumes de dados não estruturados.",
    Figma = "Collaborative design tool for creating interactive interfaces and prototypes.",
    //Ferramenta de design colaborativo para criação de interfaces e protótipos interativos.",
    Docker = "Container platform that facilitates the creation, distribution and execution of applications in isolated environments.",
    //Plataforma de contêineres que facilita a criação, distribuição e execução de aplicações em ambientes isolados.",
    Postman = "Tool for testing and documenting APIs, facilitating development and integration between services.",
    //Ferramenta para testar e documentar APIs, facilitando o desenvolvimento e a integração entre serviços.",
    SpringBoot = "Java framework that simplifies the development of backend applications with a focus on productivity and good practices.",
    //Framework Java que simplifica o desenvolvimento de aplicações backend com foco em produtividade e boas práticas.",
}

export default descriptions;