config_version = "0"

exclude_patterns = [
  "**/node_modules/**",
  "**/dist/**",
  "**/build/**",
  "**/.next/**",
  "**/coverage/**"
]

test_patterns = [
  "**/*.test.*",
  "**/*.spec.*"
]

[smells]
mode = "issue"

[[plugin]]
name = "eslint"
version = "9.12.0"
package_file = "package.json"
package_filters = [
  "eslint-plugin-react",
  "eslint-plugin-react-hooks",
  "eslint-plugin-jsx-a11y",
  "@typescript-eslint/parser",
  "@typescript-eslint/eslint-plugin"
]
args = ["--config", "eslint.config.js"]

[[plugin]]
name = "duplication"

[[plugin]]
name = "radarlint-js"

[[plugin]]
name = "trivy"
drivers = ["config", "fs-vuln"]

[[plugin]]
name = "osv-scanner"
