name: CI (Qlty)

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: 
      - main
      - develop

permissions:
  contents: read
  id-token: write # Required for OIDC

jobs:
  qlty-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Qlty CLI
        run: |
          curl -s https://qlty.sh/install.sh | bash
          echo "$HOME/.qlty/bin" >> $GITHUB_PATH

      - name: Rodar análise Qlty
        run: qlty check